"""init_indexing_schema

Revision ID: acff5bddba97
Revises: 
Create Date: 2026-02-06 13:48:52.983488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acff5bddba97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexing_action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='로그 ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='사용자 ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='그룹 ID'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='사용자 역할 ID'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='액션 타입 (CREATE, READ, UPDATE, DELETE, SEARCH, UPLOAD, DOWNLOAD)'),
    sa.Column('endpoint', sa.String(length=200), nullable=False, comment='요청된 엔드포인트 경로'),
    sa.Column('http_method', sa.String(length=10), nullable=False, comment='HTTP 메서드 (GET, POST, PUT, DELETE, WEBSOCKET)'),
    sa.Column('document_id', sa.String(length=100), nullable=True, comment='대상 문서 ID 또는 해시값'),
    sa.Column('document_title', sa.String(length=255), nullable=True, comment='문서 제목'),
    sa.Column('document_category', sa.String(length=100), nullable=True, comment='문서 카테고리'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='파일명'),
    sa.Column('file_type', sa.String(length=30), nullable=True, comment='파일 타입'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='파일 크기 (바이트)'),
    sa.Column('action_details', sa.JSON(), nullable=True, comment='액션 세부 정보 (JSON 형태)'),
    sa.Column('request_params', sa.JSON(), nullable=True, comment='요청 파라미터 (쿼리, 필터 등)'),
    sa.Column('changes_made', sa.JSON(), nullable=True, comment='변경 내용 (이전값 -> 새값)'),
    sa.Column('search_query', sa.Text(), nullable=True, comment='검색 쿼리'),
    sa.Column('search_results_count', sa.Integer(), nullable=True, comment='검색 결과 개수'),
    sa.Column('use_reranker', sa.Boolean(), nullable=True, comment='리랭커 사용 여부'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP 응답 상태 코드'),
    sa.Column('success', sa.String(length=10), nullable=False, comment='성공 여부 (SUCCESS, FAILED, ERROR)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('error_type', sa.String(length=100), nullable=True, comment='오류 타입'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='사용된 토큰 수'),
    sa.Column('cost_incurred', sa.String(length=20), nullable=True, comment='발생 비용 (USD)'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='처리 시간 (밀리초)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='클라이언트 IP 주소'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='사용자 에이전트'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='세션 ID'),
    sa.Column('task_id', sa.String(length=100), nullable=True, comment='비동기 작업 ID'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='요청 추적 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='로그 생성 시간'),
    sa.Column('request_start_time', sa.DateTime(), nullable=True, comment='요청 시작 시간'),
    sa.Column('request_end_time', sa.DateTime(), nullable=True, comment='요청 완료 시간'),
    sa.PrimaryKeyConstraint('id'),
    schema='indexing'
    )
    op.create_table('indexing_document_categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='카테고리 고유 식별자'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='카테고리 이름'),
    sa.Column('retention_period', sa.Integer(), nullable=False, comment='권장 보관 기간(단위: 년)'),
    sa.Column('description', sa.Text(), nullable=True, comment='비고 및 상세 설명'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='indexing'
    )
    op.create_index(op.f('ix_indexing_indexing_document_categories_id'), 'indexing_document_categories', ['id'], unique=False, schema='indexing')
    op.create_table('indexing_embedding_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='스케줄 ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='스케줄 이름 (시스템 자동 생성, 사용자 수정 가능)'),
    sa.Column('description', sa.Text(), nullable=True, comment='스케줄 설명'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='생성자 사용자 ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='그룹 ID'),
    sa.Column('role_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='역할 ID 배열 (스케줄 생성자의 total_role)'),
    sa.Column('document_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='임베딩할 문서의 hash_sha256 배열 (JSON)'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='예약된 실행 시간'),
    sa.Column('cron_expression', sa.String(length=100), nullable=True, comment='반복 스케줄용 Cron 표현식 (선택사항)'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='시간대'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('embedding_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='임베딩 생성 설정 (JSON)'),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 실행 시간'),
    sa.Column('total_executions', sa.Integer(), nullable=False, comment='총 실행 횟수'),
    sa.Column('successful_executions', sa.Integer(), nullable=False, comment='성공한 실행 횟수'),
    sa.Column('failed_executions', sa.Integer(), nullable=False, comment='실패한 실행 횟수'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='수정 시간'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제 시간 (Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
    schema='indexing'
    )
    op.create_table('indexing_endpoints_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False, comment='API 경로'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='리소스 타입'),
    sa.Column('required_role', sa.String(length=50), nullable=True, comment='필요 역할'),
    sa.Column('http_method', sa.String(length=10), nullable=False, comment='HTTP 메소드'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='액션 타입'),
    sa.PrimaryKeyConstraint('id'),
    schema='indexing'
    )
    op.create_table('indexing_entity_relation',
    sa.Column('id', sa.Integer(), nullable=False, comment='고유 식별자'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='그룹 ID'),
    sa.Column('source_entity', sa.String(length=255), nullable=False, comment='출발 엔티티 이름'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='출발 엔티티 타입'),
    sa.Column('relation_type', sa.String(length=100), nullable=False, comment='관계 타입 (담당함, 소속됨, ...)'),
    sa.Column('target_entity', sa.String(length=255), nullable=False, comment='도착 엔티티 이름'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='도착 엔티티 타입'),
    sa.Column('source_hash', sa.String(length=64), nullable=False, comment='관계가 추출된 문서 해시'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='생성 시간'),
    sa.PrimaryKeyConstraint('id'),
    schema='indexing'
    )
    op.create_index('ix_entity_relation_group_source', 'indexing_entity_relation', ['group_id', 'source_entity'], unique=False, schema='indexing')
    op.create_index('ix_entity_relation_group_target', 'indexing_entity_relation', ['group_id', 'target_entity'], unique=False, schema='indexing')
    op.create_index('ix_entity_relation_source_hash', 'indexing_entity_relation', ['source_hash'], unique=False, schema='indexing')
    op.create_index(op.f('ix_indexing_indexing_entity_relation_id'), 'indexing_entity_relation', ['id'], unique=False, schema='indexing')
    op.create_table('indexing_entity_type_master',
    sa.Column('id', sa.Integer(), nullable=False, comment='고유 식별자'),
    sa.Column('type_key', sa.String(length=50), nullable=False, comment='타입 키 (person, organization, ...)'),
    sa.Column('type_name', sa.String(length=100), nullable=False, comment='타입 이름 (인물, 조직, ...)'),
    sa.Column('description', sa.Text(), nullable=True, comment='타입 설명'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_key'),
    schema='indexing'
    )
    op.create_index(op.f('ix_indexing_indexing_entity_type_master_id'), 'indexing_entity_type_master', ['id'], unique=False, schema='indexing')
    op.create_table('indexing_parser_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='파서 설정 ID'),
    sa.Column('parser_name', sa.String(length=50), nullable=False, comment='파서 식별자 (예: ktc_parser)'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='표시 이름 (예: KT Cloud Document Parser)'),
    sa.Column('api_endpoint', sa.Text(), nullable=False, comment='API 엔드포인트 URL'),
    sa.Column('api_key', sa.Text(), nullable=False, comment='API 인증 키'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부 (FALSE일 경우 사용 불가)'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False, comment='API 호출 타임아웃 (초)'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='실패 시 최대 재시도 횟수'),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='파서별 추가 설정 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='수정 시간'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parser_name'),
    schema='indexing'
    )
    op.create_table('indexing_user_categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='카테고리 고유 식별자'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='소유자 사용자 ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='소속 그룹 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='카테고리 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='카테고리 설명'),
    sa.Column('default_retention_period', sa.Integer(), nullable=False, comment='만료기간 추천값 (년 단위)'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='부모 카테고리 ID'),
    sa.Column('depth', sa.Integer(), nullable=False, comment='계층 깊이 (루트=1)'),
    sa.Column('path', sa.Text(), nullable=True, comment='경로 문자열 (예: 1/5/12)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.CheckConstraint('depth >= 1', name='ck_depth_positive'),
    sa.ForeignKeyConstraint(['parent_id'], ['indexing.indexing_user_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'parent_id', name='uq_user_name_parent'),
    schema='indexing'
    )
    op.create_index('idx_user_categories_parent_id', 'indexing_user_categories', ['parent_id'], unique=False, schema='indexing')
    op.create_index('idx_user_categories_path', 'indexing_user_categories', ['path'], unique=False, schema='indexing')
    op.create_index('idx_user_categories_user_id', 'indexing_user_categories', ['user_id'], unique=False, schema='indexing')
    op.create_index(op.f('ix_indexing_indexing_user_categories_group_id'), 'indexing_user_categories', ['group_id'], unique=False, schema='indexing')
    op.create_index(op.f('ix_indexing_indexing_user_categories_id'), 'indexing_user_categories', ['id'], unique=False, schema='indexing')
    op.create_index(op.f('ix_indexing_indexing_user_categories_path'), 'indexing_user_categories', ['path'], unique=False, schema='indexing')
    op.create_index(op.f('ix_indexing_indexing_user_categories_user_id'), 'indexing_user_categories', ['user_id'], unique=False, schema='indexing')
    op.create_table('indexing_schedule_execution_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='실행 이력 ID'),
    sa.Column('schedule_id', sa.Integer(), nullable=False, comment='스케줄 ID'),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=False, comment='실행 시간'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='실행 상태 (running, success, failed, cancelled)'),
    sa.Column('documents_processed', sa.Integer(), nullable=False, comment='처리된 문서 수'),
    sa.Column('documents_success', sa.Integer(), nullable=False, comment='성공한 문서 수'),
    sa.Column('documents_failed', sa.Integer(), nullable=False, comment='실패한 문서 수'),
    sa.Column('task_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Celery 태스크 ID 목록 (JSON)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='시작 시간'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='완료 시간'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='실행 소요 시간(초)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='에러 상세 정보 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='레코드 생성 시간'),
    sa.ForeignKeyConstraint(['schedule_id'], ['indexing.indexing_embedding_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='indexing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexing_schedule_execution_history', schema='indexing')
    op.drop_index(op.f('ix_indexing_indexing_user_categories_user_id'), table_name='indexing_user_categories', schema='indexing')
    op.drop_index(op.f('ix_indexing_indexing_user_categories_path'), table_name='indexing_user_categories', schema='indexing')
    op.drop_index(op.f('ix_indexing_indexing_user_categories_id'), table_name='indexing_user_categories', schema='indexing')
    op.drop_index(op.f('ix_indexing_indexing_user_categories_group_id'), table_name='indexing_user_categories', schema='indexing')
    op.drop_index('idx_user_categories_user_id', table_name='indexing_user_categories', schema='indexing')
    op.drop_index('idx_user_categories_path', table_name='indexing_user_categories', schema='indexing')
    op.drop_index('idx_user_categories_parent_id', table_name='indexing_user_categories', schema='indexing')
    op.drop_table('indexing_user_categories', schema='indexing')
    op.drop_table('indexing_parser_config', schema='indexing')
    op.drop_index(op.f('ix_indexing_indexing_entity_type_master_id'), table_name='indexing_entity_type_master', schema='indexing')
    op.drop_table('indexing_entity_type_master', schema='indexing')
    op.drop_index(op.f('ix_indexing_indexing_entity_relation_id'), table_name='indexing_entity_relation', schema='indexing')
    op.drop_index('ix_entity_relation_source_hash', table_name='indexing_entity_relation', schema='indexing')
    op.drop_index('ix_entity_relation_group_target', table_name='indexing_entity_relation', schema='indexing')
    op.drop_index('ix_entity_relation_group_source', table_name='indexing_entity_relation', schema='indexing')
    op.drop_table('indexing_entity_relation', schema='indexing')
    op.drop_table('indexing_endpoints_permission', schema='indexing')
    op.drop_table('indexing_embedding_schedules', schema='indexing')
    op.drop_index(op.f('ix_indexing_indexing_document_categories_id'), table_name='indexing_document_categories', schema='indexing')
    op.drop_table('indexing_document_categories', schema='indexing')
    op.drop_table('indexing_action_logs', schema='indexing')
    # ### end Alembic commands ### 